name: Deploy to Docker HUB and EKS
on:

  push:
    branches: [ main ]

env:
  EKS_CLUSTER_NAME: MyEKSCluster
  AWS_REGION: us-east-1

jobs:

  build:

    name: Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Set short git commit SHA
        id: commit
        uses: prompt/actions-commit-hash@v2

      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{env.AWS_REGION}}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, tag, and push image to Amazon Docker hub
        env:
          DOCKER_HUB: luongnv1810
          IMAGE_TAG: ${{ steps.commit.outputs.short }}
        run: |
          docker build -t $DOCKER_HUB/reverseproxy:$IMAGE_TAG -f ./udagram-reverseproxy/Dockerfile ./udagram-reverseproxy
          docker push $DOCKER_HUB/reverseproxy:$IMAGE_TAG
          
          docker build -t $DOCKER_HUB/udagram-api-feed:$IMAGE_TAG -f ./udagram-api-feed/Dockerfile ./udagram-api-feed
          docker push $DOCKER_HUB/udagram-api-feed:$IMAGE_TAG
          
          docker build -t $DOCKER_HUB/udagram-api-user:$IMAGE_TAG -f ./udagram-api-user/Dockerfile ./udagram-api-user
          docker push $DOCKER_HUB/udagram-api-user:$IMAGE_TAG
          
          docker build -t $DOCKER_HUB/udagram-frontend:$IMAGE_TAG -f ./udagram-frontend/Dockerfile ./udagram-frontend
          docker push $DOCKER_HUB/udagram-frontend:$IMAGE_TAG

#      - name: Update kube config
#        run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION
#
#      - name: Deploy to EKS
#        env:
#          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#          IMAGE_TAG: ${{ steps.commit.outputs.short }}
#        run: |
#          sed -i.bak "s|DOCKER_IMAGE|$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG|g" manifests/hello-app-reverseproxy-backend-user-deployment.yaml && \
#          kubectl apply -f manifests/hello-app-reverseproxy-backend-user-deployment.yaml
#          kubectl apply -f manifests/hello-app-reverseproxy-backend-user-service.yaml